#application: kamekazi-169920
#version: 1
runtime: go
api_version: go1

handlers:
- url: /basic.css
  static_files: basic.css
  upload: basic.css
- url: /.*
  script: _go_app
  secure: always
- url: /msg/
  script: _go_app
  secure: always
